### PR TITLE
Removed redundant variable init, Constify REST URL variable, used try…

### PR DESCRIPTION
**Pull request by freesoft**
Removed redundant variable initialization, constify REST URL variable, used try-with-resources for BufferedReader.

### CODE REVIEW

**Comment by gibffe** [comment]
https://github.com/TeleSign/java_telesign/pull/27 is already refactoring executeMethod and https://github.com/TeleSign/java_telesign/pull/26 is removing string literals from method bodies

**Comment by freesoft** [comment]
Yeah see some changes in yours, although your branch need some rework for constant variable names. Btw, is this project dead by now? Pull request should be processed faster than this so that participants can avoid redundant. Wish this slowness is due to year-end holiday season.

**Comment by gibffe** [comment]
@freesoft it takes a while - hopefully we can get these pulls reviewed after the break

**Comment by hmorales** [comment]
@gibffe 
You nailed it, I was on holiday and currently the only one looking at this repo. I am in the process of reviewing pull requests today. It seems this one can be close as its already addressed but other pull requests.

**Pull request closed without merging**
