### PR TITLE
cleaning up, more maven support, deprecating ANT build

### PR DESCRIPTION
**Pull request by freesoft**
Fixed a few code  concern.
Added maven library dependencies in pom file and moved files location
to follow up maven standard convention.
Deprecating ANT build.

Those in /libs need to be deleted as well. Also common-codec-1.7
doesn’t seem to be used in the project. Maven build success without it
in the pom.

### CODE REVIEW

**Comment by gibffe** [comment]
It is impossible to review your "fixed a few code concern" if you're moving files around at the same time - if you have code fixes, submit a separate pull for that.

Deletion does not equal deprecation - please don't touch the current build system, the two can easily coexist during the transition period.

**Comment by freesoft** [comment]
Maven is convention over configuration build system. So if you guys are in transitioning period, at least change the project directory structure to follow maven one and modify Ant to use changed directory is going to make more sense. But I get it, let me recreate another branch and commit the source code change I made for clean up part. Since I did everything in one commit, it's not possible to cherrypick or revert those restructuring part. Btw, do you guys have ANT->Maven transitioning issue ticket opened now?

**Comment by gibffe** [comment]
@freesoft I am just a committer, like yourself :) 

I agree that moving to maven is a good idea - I still think we should not touch ant build for a while (apart from obvious path changes in build.xml).

**Comment by hmorales** [comment]
@gibffe & @freesoft 
First off thanks for all the contributions which are definitely needed! For now lets leave the build system alone. Internally we have been discussing the idea of completely rewriting the SDK which would introduce some backwards compatibility changes. I will open a separate ticket regarding some initial thoughts as I would greatly appreciate your feedback.

**Pull request closed without merging**
