### PR TITLE
Shared Gson instance

### PR DESCRIPTION
**Pull request by gibffe**
Gson instance is thread safe - removing unnecessary per-request instantiations. Bumping gson to 2.3.1

### CODE REVIEW

**Comment by gibffe** [comment]
Is anyone maintaining this thing ? hello ?

**Comment by hmorales** [comment]
Hello @gibffe! Thanks for the pull request. haven't taken a look at the changes yet but initial unit test are failing, see below.

  ant junit
Buildfile: /Users/hmorales/Projects/ts/java_telesign/build.xml

clean:
   [delete] Deleting directory /Users/hmorales/Projects/ts/java_telesign/build

compile_unittest:
    [mkdir] Created dir: /Users/hmorales/Projects/ts/java_telesign/build/classes
    [javac] Compiling 10 source files to /Users/hmorales/Projects/ts/java_telesign/build/classes
    [javac] Note: /Users/hmorales/Projects/ts/java_telesign/src/com/telesign/util/IpValidator.java uses unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] Compiling 4 source files to /Users/hmorales/Projects/ts/java_telesign/build/classes

jar_unit:
    [mkdir] Created dir: /Users/hmorales/Projects/ts/java_telesign/build/jar
      [jar] Building jar: /Users/hmorales/Projects/ts/java_telesign/build/jar/TeleSign.jar

junit:
    [junit] Running com.telesign.PhoneIdTest
    [junit] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 9.738 sec
    [junit] Running com.telesign.TeleSignRequestTest
    [junit] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.809 sec
    [junit] Running com.telesign.VerifyTest
    [junit] Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.389 sec
    [junit] Running com.telesign.response.ResponseTest
    [junit] Tests run: 7, **Failures:** 4, Errors: 0, Skipped: 0, Time elapsed: 0.147 sec
    [junit] Test com.telesign.response.ResponseTest **FAILED**

BUILD SUCCESSFUL
Total time: 17 seconds

**Comment by gibffe** [comment]
I'll take a look.

**Comment by gibffe** [comment]
My bad - fixed. 

Please run the suite again with your test.properties - we don't have all services enabled, so there are still some failures.

**Pull request merged**
